keyStore:
  path: classpath:sokolov.personal.p12
  type: PKCS12
  password: 1979


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${front.issuer-uri}
      client:
        provider:
          keycloak:
            issuer-uri: ${front.issuer-uri}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${front.client-id}
            client-secret: ${front.client-secret}
            scope: openid
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

#-----------------------------------------------------------------------------
server:
  port: 9000
  ssl:
    certificate: "classpath:localhost.crt"
    certificate-private-key: "classpath:localhost.key"
    client-auth: need

#-----------------------------------------------------------------------------
db:
  url: jdbc:postgresql://localhost:5433/postgres?currentSchema=kcusers
  username: postgres
  password: ${pgpwd:admin}

#-----------------------------------------------------------------------------
front:
  issuer-uri: https://keycloak.local/realms/APIM
  client-id: kcusers_servlet_client
  client-secret: ${clsec:pBK7LX5NvP3SBoVNUJNty4Cci3jRSNWC}
  userroles: user
  adminroles: admin

#-----------------------------------------------------------------------------
service:
  cron: 00 * * * * *
  keycloakclient:
    realms: master,APIM,Finstar
    url: https://keycloak.local
    client:
      client-id: kcusers_service_client
      client-secret: ${sclsec:4SHmwheAqTTtmdPeEmdrWM5lurouxrop}
    admin:
      realm: master # управление другими realm возможно только из master
      #login: admin
      #password: ${kсpwd:admin}
    inactivity:
      protectedusers:
        - admin
        - yetanotheradmin
      days: 90
      immunityperiodminutes: 240
      dryrun: false

#-----------------------------------------------------------------------------
consul:
  enabled: false
  url: "http://localhost:8500"
  acltoken: "1f57b9dc-e104-8843-519b-7f795bc8a364"
  service:
    id: "kcusers"
    name: "kcusers"
    host: "https://kcusers.local"
    port: 443
    delay: 10000
    ttl: 15000
    tags:
      - APIM
      - kcusers
      - keycloak
      - МС Управления пользователями
    note: "kcusers alive and reachable"
