spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${front.issuer-uri}
      client:
        provider:
          keycloak:
            issuer-uri: ${front.issuer-uri}
            user-name-attribute: preferred_username

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432,xeon.lan:5432/kcusers

  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  web:
    resources:
      add-mappings: false


#-----------------------------------------------------------------------------
server:
  port: 9000
#  ssl: ----- loading from Vault
#    certificate: "classpath:localhost.crt"
#    certificate-private-key: "classpath:localhost.key"
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: 1979

#    client-auth: need
#    trust-certificate: classpath:sokolov.personal.ca2.crt


#-----------------------------------------------------------------------------
front:
  issuer-uri: https://keycloak.local/realms/APIM
  #client-id: kcusers_servlet_client
  #client-secret: ${clsec:pBK7LX5NvP3SBoVNUJNty4Cci3jRSNWC}
  userroles: user
  adminroles: admin

#-----------------------------------------------------------------------------
service:
  #cron: 0 */2 * * * *
  #cron: 0 1-59/2 * * * *
  cron: 0 * * * * *
  keycloakclient:
    realms: master,APIM,APIM_FS
    url: https://keycloak.local
    client:
      client-id: kcusers_service_client
      client-secret: ${sclsec:4SHmwheAqTTtmdPeEmdrWM5lurouxrop}
    admin:
      realm: master # управление другими realm возможно только из master
      #login: admin
      #password: ${kсpwd:admin}
    inactivity:
      protectedusers:
        - admin
        - yetanotheradmin
      days: 90
      immunityperiodminutes: 240
      dryrun: false
    mtls:
      enabled: false
      keyStore:
        path: classpath:sokolov.personal.p12
        type: PKCS12
        password: 1979

#-----------------------------------------------------------------------------
consul:
  enabled: false
  url: "http://localhost:8500"
  acltoken: "1f57b9dc-e104-8843-519b-7f795bc8a364"
  service:
    id: "kcusers"
    name: "kcusers"
    host: "https://kcusers.local"
    port: 443
    delay: 10000
    ttl: 15000
    tags:
      - APIM
      - kcusers
      - keycloak
      - МС Управления пользователями
    note: "kcusers alive and reachable"

vault:
  enabled: true
  uri: https://localhost:8200
  ssl:
    # store/cert
    type: cert
#    key-store: classpath:localhost.p12
#    key-store-type: PKCS12
#    key-store-password: 1979
    certificate: classpath:sokolov.personal.ca2.crt
    key: classpath:sokolov.personal.ca2.key
  paths:
    apim:
      apps:
        kcusers:
          config:
            db-username: spring.datasource.username
            db-password: spring.datasource.password
            service-keycloak-client-secret: service.keycloakclient.client.client-secret
          certificates:
            tls:
              server:
                certificate: server.ssl.certificate
                privateKey: server.ssl.certificate-private-key
